name: checks

on:
  push:
    branches:
      - master
      - release-v*
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: github.repository != 'OpenZeppelin/openzeppelin-contracts-upgradeable'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: npm run lint

  tests:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      GAS: true
      GAS_REPORT: HEAD.gasreport.log~
      REF_REPORT: ${{ github.base_ref }}.gasreport.log
      OUT_REPORT: ${{ github.ref_name }}.gasreport.log
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run tests and generate gas report
        run: npm run test
      - name: Check linearisation of the inheritance graph
        run: npm run test:inheritance
      - name: Check proceduraly generated contracts are up-to-date
        if: github.repository != 'OpenZeppelin/openzeppelin-contracts-upgradeable'
        run: npm run test:generation
      - name: 'Download reference report'
        if: github.event_name == 'pull_request'
        run: |
          RUN_ID=`gh run list --repo ${{ github.repository }} --branch ${{ github.base_ref }} --workflow ${{ github.workflow }} --json 'conclusion,databaseId' --jq 'map(select(.conclusion=="success"))[0].databaseId'`
          gh run download ${RUN_ID} --repo ${{ github.repository }} -n gasreport
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Compare reports'
        if: github.event_name == 'pull_request'
        run: node scripts/checks/compareGasReports.js $GAS_REPORT $REF_REPORT >> $GITHUB_STEP_SUMMARY
      - name: 'Rename report for upload'
        if: github.event_name != 'pull_request'
        run: |
          mv $GAS_REPORT $OUT_REPORT
      - name: 'Save report'
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: gasreport
          path: ${{ env.OUT_REPORT }}

  coverage:
    if: github.repository != 'OpenZeppelin/openzeppelin-contracts-upgradeable'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: npm run coverage
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - uses: codecov/codecov-action@v3

  slither:
    if: github.repository != 'OpenZeppelin/openzeppelin-contracts-upgradeable'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - uses: crytic/slither-action@v0.1.1
